import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const notoSansKR = Noto_Sans_KR({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Myyyy Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	users: React.ReactNode;
	trends: React.ReactNode;
}

export default function RootLayout({
	children,
	users,
	trends,
}: Readonly<RootLayoutProps>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.className} antialiased max-w-[560px] m-auto ${notoSansKR.className}`}
			>
				<nav className="py-4 flex gap-4">
					<Link href="/">Home</Link>
					<Link href="/feed">Feed</Link>
					<Link href="/search">Search</Link>
					<Link href="/setting">Setting</Link>
				</nav>
				<div className="flex gap-4">
					<main style={{ flex: 2 }}> {children}</main>
					<div className="flex gap-4 flex-col flex-1">
						{users}
						{trends}
					</div>
				</div>
			</body>
		</html>
	);
}
